[tool.ruff]
# Basic settings
line-length = 220
target-version = "py310"

# Keep empty lines between dictionary definitions
[tool.ruff.lint]
select = ["E", "F", "W"]  # Example linting rules

[tool.ruff.format]
# Use double quotes for strings
quote-style = "double"
# Keep multiline if statements as written
skip-magic-trailing-comma = false
# Prevent breaking lines unnecessarily
line-ending = "auto"
# Use 4 spaces for indentation
indent-style = "space"
# This is what you need to preserve blank lines
empty-line-after-nested-class-or-def = true

# You might also need this option
[tool.ruff.lint.isort]
lines-after-imports = 2  # Adjust as needed

# Most importantly, add this custom rule
[tool.ruff.per-file-ignores]
"*.py" = ["E303"]  # Ignore "too many blank lines" errors
